# Hacker Underground

[window]
padding = { x = 8, y = 6 }
decorations = "full"  # Sin bordes, full pantalla
opacity = 1.0
blur = false
title = "root@hackermode"

[font]
normal = { family = "Hermit", style = "Regular" }  # Legibilidad hacker
bold = { family = "Hermit", style = "Bold" }
size = 12.0  # Tamaño clásico
offset = { x = -1, y = 0 }

# Configuración del cursor
[cursor]
  style = { shape = "Beam", blinking = "Always" }
  vi_mode_style = "None"
  blink_interval = 500
  unfocused_hollow = true
  thickness = 0.15

[bell]
  animation = "EaseOutExpo"
  duration = 300
  color = "#8A2BE2"
  command = "None"

# Opciones de Mouse
[mouse]
  hide_when_typing = false

[colors]
  draw_bold_text_with_bright_colors = true
  [colors.primary]
  background = "0x000000"
  foreground = "0x00FF00"

  [colors.normal]
  black = "0x000000"
  red = "0xFF0000"
  green = "0x00FF00"
  yellow = "0xCCCC00"
  blue = "0x0066CC"
  magenta = "0x7700AA"
  cyan = "0x00CCCC"
  white = "0xBBBBBB"

  [colors.bright]
  black = "0x333333"
  red = "0xFF3333"
  green = "0x00FF00"
  yellow = "0xFFFF00"
  blue = "0x0066FF"
  magenta = "0x9900FF"
  cyan = "0x00FFFF"
  white = "0xDDDDDD"
